package main

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"log"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/spf13/cobra"
)

const (
	defaultListenAddr   = "127.0.0.1:0"
	defaultMaxFileBytes = 1024 * 1024
	maxBodyBytes        = 1 << 20
	shutdownTimeout     = 10 * time.Second
	sandboxEnvVar       = "LOCALFILES_MCP_SANDBOX_ACTIVE"
)

type cliConfig struct {
	Root              string
	Listen            string
	Token             string
	Exclude           string
	ExcludeRegex      string
	ExcludeDotfiles   bool
	MaxFileBytes      int64
	NoTui             bool
	TailscaleExpose   bool
	NoTailscale       bool
	TailscalePath     string
	TailscalePort     int
	TailscaleHostname string
	TLSCert           string
	TLSKey            string
	Sandbox           bool
	SandboxProfile    string
}

func main() {
	if err := run(); err != nil {
		log.Printf("server terminated: %v", err)
		os.Exit(1)
	}
}

func run() error {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGINT, syscall.SIGTERM, syscall.SIGHUP)
	defer stop()

	cfg, err := parseCLIArgs(os.Args[1:])
	if err != nil {
		return fmt.Errorf("parse flags: %w", err)
	}

	exposedActive := cfg.TailscaleExpose && !cfg.NoTailscale
	listenArg := cfg.Listen
	resolvedRoot, err := resolveRootDir(cfg.Root)
	if err != nil {
		return fmt.Errorf("resolve root directory: %w", err)
	}
	cfg.Root = resolvedRoot

	if cfg.Sandbox && !isSandboxedProcess() {
		if err := launchInAppleSandbox(cfg); err != nil {
			return fmt.Errorf("launch apple sandbox: %w", err)
		}
		return nil
	}

	authToken := strings.TrimSpace(cfg.Token)
	authTokenFromEnv := strings.TrimSpace(os.Getenv("LOCALFILES_MCP_TOKEN"))
	if authToken == "" {
		authToken = authTokenFromEnv
	}
	tokenAutoGenerated := false
	if authToken == "" {
		generated, tokenErr := generateToken()
		if tokenErr != nil {
			return fmt.Errorf("generate token: %w", tokenErr)
		}
		authToken = generated
		tokenAutoGenerated = true
	}
	if authToken == "" {
		// defensive fallback for impossible states only
		return errors.New("auth token is required")
	}

	exposedPath := normalizeTailscalePath(cfg.TailscalePath)
	remoteURL := ""
	var cleanupOnce sync.Once
	var tailscaleSession *TailscaleSession
	var discoveredHostname string

	cleanup := func() {
		cleanupOnce.Do(func() {
			if tailscaleSession != nil {
				if err := tailscaleSession.Teardown(); err != nil {
					log.Printf("tailscale cleanup failed: %v", err)
				}
			}
		})
	}
	defer cleanup()

	listener, err := net.Listen("tcp", listenArg)
	if err != nil {
		return fmt.Errorf("listen on %s: %w", listenArg, err)
	}
	listenArg = listener.Addr().String()
	defer listener.Close()

	if exposedActive {
		if strings.TrimSpace(cfg.TailscaleHostname) != "" {
			discoveredHostname = strings.TrimSpace(cfg.TailscaleHostname)
		} else {
			detected, hostErr := discoverTailscaleHostname()
			if hostErr != nil {
				log.Printf("auto-detecting tailscale hostname failed: %v", hostErr)
			} else {
				discoveredHostname = detected
			}
		}

		if discoveredHostname == "" {
			discoveredHostname = "<discover-your-hostname>"
		}
		remoteURL = formatTailscaleURL(discoveredHostname, cfg.TailscalePort, exposedPath)

		tailscaleSession, err = NewTailscaleSession(TailscaleSessionConfig{
			Path:      exposedPath,
			Listen:    listenArg,
			HttpsPort: cfg.TailscalePort,
			Runner:    runShellCommand,
		})
		if err != nil {
			return fmt.Errorf("prepare tailscale expose session: %w", err)
		}
		if err := tailscaleSession.Expose(); err != nil {
			return fmt.Errorf("expose with tailscale serve: %w", err)
		}
	}

	var eventCh chan MCPEvent
	if !cfg.NoTui {
		eventCh = make(chan MCPEvent, 256)
	}

	var onEvent func(MCPEvent)
	if eventCh != nil {
		onEvent = func(evt MCPEvent) {
			select {
			case eventCh <- evt:
			default:
			}
		}
	}

	server, err := NewMCPServer(MCPConfig{
		Root:            resolvedRoot,
		AuthToken:       authToken,
		ExcludeDotfiles: cfg.ExcludeDotfiles,
		ExcludeRegex:    mergeExcludePattern(cfg.Exclude, cfg.ExcludeRegex),
		MaxFileBytes:    cfg.MaxFileBytes,
		AllowedOrigins:  buildExplicitAllowedOrigins(remoteURL),
		OnEvent:         onEvent,
	})
	if err != nil {
		return fmt.Errorf("initialize server: %w", err)
	}

	var dashboard *MCPDashboard
	if !cfg.NoTui {
		localURL := fmt.Sprintf("http://%s/mcp", listenArg)
		dashboard = NewMCPDashboard(MCPDashboardConfig{
			LocalURL:           localURL,
			RemoteURL:          remoteURL,
			RootDir:            resolvedRoot,
			ExposePath:         exposedPath,
			ExposeActive:       exposedActive,
			AuthToken:          authToken,
			TokenAutoGenerated: tokenAutoGenerated,
			TailscaleHost:      discoveredHostname,
			TailscalePort:      cfg.TailscalePort,
		})
		dashboard.Start(ctx, eventCh)
	}

	if cfg.NoTui {
		log.Printf("localfiles-mcp: serving %s on %s", resolvedRoot, listenArg)
		log.Printf("MCP endpoint: http://%s/mcp", listenArg)
		log.Printf("Attach to ChatGPT in: Settings > Advanced > Model Context Protocol")
		log.Printf("MCP URL: %s", formatMCPInstructionEndpoint(exposedActive, remoteURL, listenArg))
		log.Printf("Authorization header: Authorization: Bearer %s", authToken)
		log.Printf("auth token: %s", authToken)
		if exposedActive {
			log.Printf("tailscale endpoint: %s", remoteURL)
		}
	}

	if (cfg.TLSCert == "") != (cfg.TLSKey == "") {
		return errors.New("both -tls-cert and -tls-key are required together")
	}

	mux := http.NewServeMux()
	mux.Handle("/mcp", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if rec := recover(); rec != nil {
				http.Error(w, "internal server error", http.StatusInternalServerError)
			}
		}()
		server.ServeHTTP(w, r)
	}))
	mux.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok"))
	})

	srv := &http.Server{
		Handler:           mux,
		ReadHeaderTimeout: 5 * time.Second,
		ReadTimeout:       30 * time.Second,
		WriteTimeout:      30 * time.Second,
		IdleTimeout:       120 * time.Second,
		MaxHeaderBytes:    1 << 20,
	}

	serverErr := make(chan error, 1)
	go func() {
		if cfg.TLSCert != "" {
			serverErr <- srv.ServeTLS(listener, cfg.TLSCert, cfg.TLSKey)
			return
		}
		serverErr <- srv.Serve(listener)
	}()

	err = func() error {
		select {
		case <-ctx.Done():
			shutdownCtx, cancel := context.WithTimeout(context.Background(), shutdownTimeout)
			defer cancel()
			return srv.Shutdown(shutdownCtx)
		case err := <-serverErr:
			if err != nil && err != http.ErrServerClosed {
				return err
			}
			return nil
		}
	}()
	if dashboard != nil {
		dashboard.Stop()
	}
	if err != nil {
		return fmt.Errorf("server exited: %w", err)
	}
	return nil
}

func resolveRootDir(raw string) (string, error) {
	if strings.TrimSpace(raw) != "" {
		return filepath.Abs(filepath.Clean(raw))
	}
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	return filepath.Abs(filepath.Clean(cwd))
}

func generateToken() (string, error) {
	b := make([]byte, 24)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func parseCLIArgs(raw []string) (cliConfig, error) {
	cfg := cliConfig{
		Listen:          defaultListenAddr,
		ExcludeDotfiles: true,
		MaxFileBytes:    defaultMaxFileBytes,
		TailscaleExpose: false,
		TailscalePath:   "/mcp",
		TailscalePort:   443,
		Sandbox:         runtime.GOOS == "darwin",
	}

	cmd := &cobra.Command{
		Use:           "mcp-localfiles [root] [listen]",
		SilenceErrors: true,
		SilenceUsage:  true,
	}
	cmd.Flags().String("root", "", "Directory to expose via MCP (defaults to current working directory)")
	cmd.Flags().String("listen", defaultListenAddr, "Address to bind, e.g. 127.0.0.1:8080 or 0.0.0.0:8080")
	cmd.Flags().String("token", "", "Bearer token required by MCP clients. Can also be set via LOCALFILES_MCP_TOKEN")
	cmd.Flags().Bool("exclude-dotfiles", true, "Exclude dotfiles and hidden directories from all responses")
	cmd.Flags().String("exclude", "", "Regular expression for excluded paths; merged with --exclude-regex using OR")
	cmd.Flags().String("exclude-regex", "", "Go regular expression for excluded paths; merged with --exclude using OR")
	cmd.Flags().Int64("max-file-bytes", defaultMaxFileBytes, "Maximum file bytes returned per read_file call")
	cmd.Flags().Bool("no-tui", false, "Disable terminal UI (not recommended for local interactive use)")
	cmd.Flags().Bool("tailscale-expose", false, "Expose /mcp using `tailscale serve`")
	cmd.Flags().Bool("no-tailscale", false, "Disable Tailscale expose")
	cmd.Flags().String("tailscale-path", "/mcp", "Path to expose via tailscale serve")
	cmd.Flags().Int("tailscale-port", 443, "HTTPS port used by tailscale serve")
	cmd.Flags().String("tailscale-hostname", "", "Optional Tailscale hostname for display and remote endpoint")
	cmd.Flags().String("tls-cert", "", "Optional TLS certificate path (enables HTTPS if used with -tls-key)")
	cmd.Flags().String("tls-key", "", "Optional TLS key path (enables HTTPS if used with -tls-cert)")
	cmd.Flags().Bool("sandbox", runtime.GOOS == "darwin", "Run within Apple sandbox-exec (macOS only)")
	cmd.Flags().String("sandbox-profile", "", "Custom Apple sandbox profile path to use with --sandbox")

	if err := cmd.ParseFlags(raw); err != nil {
		return cliConfig{}, err
	}

	rootFlag := cmd.Flags().Lookup("root")
	listenFlag := cmd.Flags().Lookup("listen")

	var err error
	cfg.Root, err = cmd.Flags().GetString("root")
	if err != nil {
		return cliConfig{}, err
	}
	cfg.Listen, err = cmd.Flags().GetString("listen")
	if err != nil {
		return cliConfig{}, err
	}
	cfg.Token, err = cmd.Flags().GetString("token")
	if err != nil {
		return cliConfig{}, err
	}
	cfg.Exclude, err = cmd.Flags().GetString("exclude")
	if err != nil {
		return cliConfig{}, err
	}
	cfg.ExcludeRegex, err = cmd.Flags().GetString("exclude-regex")
	if err != nil {
		return cliConfig{}, err
	}
	cfg.ExcludeDotfiles, err = cmd.Flags().GetBool("exclude-dotfiles")
	if err != nil {
		return cliConfig{}, err
	}
	cfg.MaxFileBytes, err = cmd.Flags().GetInt64("max-file-bytes")
	if err != nil {
		return cliConfig{}, err
	}
	cfg.NoTui, err = cmd.Flags().GetBool("no-tui")
	if err != nil {
		return cliConfig{}, err
	}
	cfg.TailscaleExpose, err = cmd.Flags().GetBool("tailscale-expose")
	if err != nil {
		return cliConfig{}, err
	}
	cfg.NoTailscale, err = cmd.Flags().GetBool("no-tailscale")
	if err != nil {
		return cliConfig{}, err
	}
	cfg.TailscalePath, err = cmd.Flags().GetString("tailscale-path")
	if err != nil {
		return cliConfig{}, err
	}
	cfg.TailscalePort, err = cmd.Flags().GetInt("tailscale-port")
	if err != nil {
		return cliConfig{}, err
	}
	cfg.TailscaleHostname, err = cmd.Flags().GetString("tailscale-hostname")
	if err != nil {
		return cliConfig{}, err
	}
	cfg.TLSCert, err = cmd.Flags().GetString("tls-cert")
	if err != nil {
		return cliConfig{}, err
	}
	cfg.TLSKey, err = cmd.Flags().GetString("tls-key")
	if err != nil {
		return cliConfig{}, err
	}
	cfg.Sandbox, err = cmd.Flags().GetBool("sandbox")
	if err != nil {
		return cliConfig{}, err
	}
	cfg.SandboxProfile, err = cmd.Flags().GetString("sandbox-profile")
	if err != nil {
		return cliConfig{}, err
	}

	args := cmd.Flags().Args()
	cfg.Root = strings.TrimSpace(cfg.Root)
	cfg.Listen = strings.TrimSpace(cfg.Listen)
	cfg.Token = strings.TrimSpace(cfg.Token)
	cfg.Exclude = strings.TrimSpace(cfg.Exclude)
	cfg.ExcludeRegex = strings.TrimSpace(cfg.ExcludeRegex)
	cfg.TailscalePath = strings.TrimSpace(cfg.TailscalePath)
	cfg.TailscaleHostname = strings.TrimSpace(cfg.TailscaleHostname)
	cfg.TLSCert = strings.TrimSpace(cfg.TLSCert)
	cfg.TLSKey = strings.TrimSpace(cfg.TLSKey)
	cfg.SandboxProfile = strings.TrimSpace(cfg.SandboxProfile)

	if !rootFlag.Changed {
		if envRoot := strings.TrimSpace(os.Getenv("LOCALFILES_MCP_ROOT")); envRoot != "" {
			cfg.Root = envRoot
		}
		if len(args) >= 1 {
			cfg.Root = args[0]
		}
	}
	if !listenFlag.Changed && len(args) >= 2 {
		cfg.Listen = args[1]
	}

	cfg.Root = strings.TrimSpace(cfg.Root)
	cfg.Listen = strings.TrimSpace(cfg.Listen)

	return cfg, nil
}

func isSandboxedProcess() bool {
	return os.Getenv(sandboxEnvVar) == "1"
}

func launchInAppleSandbox(cfg cliConfig) error {
	if runtime.GOOS != "darwin" {
		return errors.New("sandbox mode is only supported on macOS")
	}
	if _, err := exec.LookPath("sandbox-exec"); err != nil {
		return fmt.Errorf("sandbox-exec must be available in PATH for --sandbox mode: %w", err)
	}

	executablePath, err := os.Executable()
	if err != nil {
		return fmt.Errorf("resolve executable path: %w", err)
	}
	if absPath, err := filepath.Abs(executablePath); err == nil {
		executablePath = absPath
	}
	if resolvedPath, err := filepath.EvalSymlinks(executablePath); err == nil {
		executablePath = resolvedPath
	}

	profilePath, cleanupProfile, err := resolveSandboxProfile(cfg, executablePath)
	if err != nil {
		return fmt.Errorf("prepare sandbox profile: %w", err)
	}
	if cleanupProfile != nil {
		defer func() {
			if err := cleanupProfile(); err != nil {
				log.Printf("warning: failed to remove temporary sandbox profile: %v", err)
			}
		}()
	}

	args := buildSandboxArgvForRelaunch(cfg)
	args = append([]string{"-f", profilePath, "--", executablePath}, args...)
	cmd := exec.Command("sandbox-exec", args...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Env = append(os.Environ(), sandboxEnvVar+"=1")

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("sandbox-exec: %w", err)
	}
	return nil
}

func resolveSandboxProfile(cfg cliConfig, executablePath string) (string, func() error, error) {
	if strings.TrimSpace(cfg.SandboxProfile) != "" {
		profilePath := strings.TrimSpace(cfg.SandboxProfile)
		if !filepath.IsAbs(profilePath) {
			var err error
			profilePath, err = filepath.Abs(profilePath)
			if err != nil {
				return "", nil, fmt.Errorf("resolve sandbox profile path: %w", err)
			}
		}
		if _, err := os.Stat(profilePath); err != nil {
			return "", nil, fmt.Errorf("read sandbox profile %s: %w", profilePath, err)
		}
		return profilePath, nil, nil
	}

	exposeActive := cfg.TailscaleExpose && !cfg.NoTailscale
	tailscalePath := ""
	if exposeActive {
		if path, err := exec.LookPath("tailscale"); err == nil {
			tailscalePath = path
		}
	}

	profile := buildAppleSandboxProfile(cfg.Root, executablePath, tailscalePath)
	tmp, err := os.CreateTemp("", "localfiles-mcp-sandbox-*.sb")
	if err != nil {
		return "", nil, fmt.Errorf("create sandbox profile temp file: %w", err)
	}

	cleanup := func() error {
		return os.Remove(tmp.Name())
	}
	if _, err := tmp.WriteString(profile); err != nil {
		_ = tmp.Close()
		_ = cleanup()
		return "", nil, fmt.Errorf("write sandbox profile: %w", err)
	}
	if err := tmp.Close(); err != nil {
		_ = cleanup()
		return "", nil, fmt.Errorf("close sandbox profile: %w", err)
	}
	return tmp.Name(), cleanup, nil
}

func buildAppleSandboxProfile(rootDir, executablePath, tailscalePath string) string {
	var b strings.Builder
	_, _ = b.WriteString("(version 1)\n")
	_, _ = b.WriteString("(import \"bsd.sb\")\n")
	_, _ = b.WriteString("\n")

	_, _ = b.WriteString("(allow file-read* (literal ")
	_, _ = b.WriteString(strconv.Quote(executablePath))
	_, _ = b.WriteString(")\n       (subpath ")
	_, _ = b.WriteString(strconv.Quote(rootDir))
	_, _ = b.WriteString(")\n       (subpath ")
	_, _ = b.WriteString(strconv.Quote("/dev"))
	_, _ = b.WriteString("))\n\n")

	_, _ = b.WriteString("(allow file-write* (subpath ")
	_, _ = b.WriteString(strconv.Quote("/dev"))
	_, _ = b.WriteString("))\n\n")

	_, _ = b.WriteString("(allow file-ioctl (subpath ")
	_, _ = b.WriteString(strconv.Quote("/dev"))
	_, _ = b.WriteString("))\n\n")

	_, _ = b.WriteString("(allow process-exec (literal ")
	_, _ = b.WriteString(strconv.Quote(executablePath))
	_, _ = b.WriteString("))\n")
	if strings.TrimSpace(tailscalePath) != "" {
		_, _ = b.WriteString("(allow process-exec (literal ")
		_, _ = b.WriteString(strconv.Quote(tailscalePath))
		_, _ = b.WriteString("))\n")
	}
	_, _ = b.WriteString("\n")
	_, _ = b.WriteString("(allow network-inbound (local ip))\n")
	_, _ = b.WriteString("(allow network-outbound)\n")
	_, _ = b.WriteString("(allow process-fork)\n")
	return b.String()
}

func buildSandboxArgvForRelaunch(cfg cliConfig) []string {
	args := []string{
		"--root", cfg.Root,
		"--listen", cfg.Listen,
		fmt.Sprintf("--exclude-dotfiles=%t", cfg.ExcludeDotfiles),
		"--max-file-bytes", strconv.FormatInt(cfg.MaxFileBytes, 10),
		fmt.Sprintf("--no-tui=%t", cfg.NoTui),
		fmt.Sprintf("--tailscale-expose=%t", cfg.TailscaleExpose),
		fmt.Sprintf("--no-tailscale=%t", cfg.NoTailscale),
		"--tailscale-path", cfg.TailscalePath,
		"--tailscale-port", strconv.Itoa(cfg.TailscalePort),
	}

	if strings.TrimSpace(cfg.Token) != "" {
		args = append(args, "--token", cfg.Token)
	}
	if strings.TrimSpace(cfg.Exclude) != "" {
		args = append(args, "--exclude", cfg.Exclude)
	}
	if strings.TrimSpace(cfg.ExcludeRegex) != "" {
		args = append(args, "--exclude-regex", cfg.ExcludeRegex)
	}
	if strings.TrimSpace(cfg.TailscaleHostname) != "" {
		args = append(args, "--tailscale-hostname", cfg.TailscaleHostname)
	}
	if strings.TrimSpace(cfg.TLSCert) != "" {
		args = append(args, "--tls-cert", cfg.TLSCert)
	}
	if strings.TrimSpace(cfg.TLSKey) != "" {
		args = append(args, "--tls-key", cfg.TLSKey)
	}
	if strings.TrimSpace(cfg.SandboxProfile) != "" {
		args = append(args, "--sandbox-profile", cfg.SandboxProfile)
	}
	return args
}

func formatTailscaleURL(hostname string, port int, path string) string {
	if strings.TrimSpace(hostname) == "" {
		hostname = "<discover-your-hostname>"
	}
	if port <= 0 || port == 443 {
		return fmt.Sprintf("https://%s%s", hostname, path)
	}
	return fmt.Sprintf("https://%s:%d%s", hostname, port, path)
}

func formatMCPInstructionEndpoint(exposed bool, remoteURL string, listenArg string) string {
	if exposed && strings.TrimSpace(remoteURL) != "" {
		return remoteURL
	}
	if strings.TrimSpace(listenArg) == "" {
		return "<local-endpoint>"
	}
	return fmt.Sprintf("http://%s/mcp", listenArg)
}

func buildExplicitAllowedOrigins(remoteURL string) []string {
	origin, err := originFromURL(remoteURL)
	if err != nil || origin == "" {
		return nil
	}
	return []string{origin}
}

func originFromURL(raw string) (string, error) {
	value := strings.TrimSpace(raw)
	if value == "" {
		return "", nil
	}
	parsed, err := url.Parse(value)
	if err != nil {
		return "", err
	}
	if parsed.Scheme == "" || parsed.Host == "" {
		return "", errors.New("url must include scheme and host")
	}
	return fmt.Sprintf("%s://%s", strings.ToLower(parsed.Scheme), strings.ToLower(parsed.Host)), nil
}

func mergeExcludePattern(exclude string, excludeRegex string) string {
	exclude = strings.TrimSpace(exclude)
	excludeRegex = strings.TrimSpace(excludeRegex)
	if exclude == "" {
		return excludeRegex
	}
	if excludeRegex == "" {
		return exclude
	}
	return fmt.Sprintf("(?:%s)|(?:%s)", exclude, excludeRegex)
}
