package main

import (
	"context"
	"fmt"
	"log"
	"strings"
	"sync"
	"time"
	"unicode/utf8"

	tea "charm.land/bubbletea/v2"
	"github.com/charmbracelet/lipgloss"
)

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const (
	tuiRefreshMs   = 200 * time.Millisecond
	tuiLogCapacity = 200
	inspectorRows  = 12
)

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

var (
	// Top and bottom bars
	barStyle = lipgloss.NewStyle().
			Background(lipgloss.Color("236")).
			Foreground(lipgloss.Color("252")).
			Padding(0, 1)
	barAccent = lipgloss.NewStyle().
			Background(lipgloss.Color("236")).
			Foreground(lipgloss.Color("117")).
			Bold(true).
			Padding(0, 1)
	barDim = lipgloss.NewStyle().
		Background(lipgloss.Color("236")).
		Foreground(lipgloss.Color("243")).
		Padding(0, 0)
	liveIndicator = lipgloss.NewStyle().
			Background(lipgloss.Color("236")).
			Foreground(lipgloss.Color("114")).
			Bold(true)
	pausedIndicator = lipgloss.NewStyle().
			Background(lipgloss.Color("236")).
			Foreground(lipgloss.Color("220")).
			Bold(true)

	// Table header
	tableHeaderStyle = lipgloss.NewStyle().
				Bold(true).
				Foreground(lipgloss.Color("252")).
				Background(lipgloss.Color("238"))

	// Table rows
	rowNormal   = lipgloss.NewStyle().Foreground(lipgloss.Color("252"))
	rowSelected = lipgloss.NewStyle().Background(lipgloss.Color("24")).Foreground(lipgloss.Color("255"))
	rowOk       = lipgloss.NewStyle().Foreground(lipgloss.Color("114"))
	rowError    = lipgloss.NewStyle().Foreground(lipgloss.Color("203"))
	rowUnauth   = lipgloss.NewStyle().Foreground(lipgloss.Color("220"))
	rowDim      = lipgloss.NewStyle().Foreground(lipgloss.Color("243"))

	// Inspector
	inspectorBorder = lipgloss.NewStyle().
			Border(lipgloss.RoundedBorder()).
			BorderForeground(lipgloss.Color("240")).
			Padding(0, 1)
	inspectorLabel = lipgloss.NewStyle().
			Foreground(lipgloss.Color("243")).
			Width(12)
	inspectorValue = lipgloss.NewStyle().
			Foreground(lipgloss.Color("252"))
	inspectorSection = lipgloss.NewStyle().
				Foreground(lipgloss.Color("117")).
				Bold(true)

	// Filter
	filterPrompt = lipgloss.NewStyle().
			Background(lipgloss.Color("236")).
			Foreground(lipgloss.Color("220")).
			Bold(true)
	filterInput = lipgloss.NewStyle().
			Background(lipgloss.Color("236")).
			Foreground(lipgloss.Color("255"))

	// Setup screen
	setupHeader = lipgloss.NewStyle().
			Foreground(lipgloss.Color("117")).
			Bold(true)
	setupDim = lipgloss.NewStyle().
			Foreground(lipgloss.Color("243"))
	setupValue = lipgloss.NewStyle().
			Foreground(lipgloss.Color("255"))
)

// ---------------------------------------------------------------------------
// TUI mode
// ---------------------------------------------------------------------------

type tuiMode int

const (
	modeNormal tuiMode = iota
	modeFilter
)

// ---------------------------------------------------------------------------
// Config & Dashboard
// ---------------------------------------------------------------------------

type MCPDashboardConfig struct {
	LocalURL           string
	RemoteURL          string
	RootDir            string
	ExposePath         string
	ExposeActive       bool
	AuthToken          string
	TokenAutoGenerated bool
	TailscaleHost      string
	TailscalePort      int
}

type MCPDashboard struct {
	localURL           string
	remoteURL          string
	rootDir            string
	exposePath         string
	exposeActive       bool
	authToken          string
	tokenAutoGenerated bool
	tailscaleHost      string
	tailscalePort      int

	startedAt time.Time

	mu sync.Mutex

	events   []MCPEvent
	reqCount int
	okCount  int
	errCount int
	unauth   int

	selected int
	expanded bool
	viewport int
	paused   bool
	mode     tuiMode
	filter   string
	program  *tea.Program
	stopOnce sync.Once
}

type mcpDashboardMsg struct {
	typ string
	evt MCPEvent
}

type tickMsg time.Time

type mcpDashboardModel struct {
	dashboard *MCPDashboard
	width     int
	height    int
}

func NewMCPDashboard(cfg MCPDashboardConfig) *MCPDashboard {
	remote := cfg.RemoteURL
	if remote == "" {
		remote = "not exposed"
	}
	return &MCPDashboard{
		localURL:           cfg.LocalURL,
		remoteURL:          remote,
		rootDir:            cfg.RootDir,
		exposePath:         cfg.ExposePath,
		exposeActive:       cfg.ExposeActive,
		authToken:          cfg.AuthToken,
		tokenAutoGenerated: cfg.TokenAutoGenerated,
		tailscaleHost:      cfg.TailscaleHost,
		tailscalePort:      cfg.TailscalePort,
		startedAt:          time.Now(),
		events:             make([]MCPEvent, 0, tuiLogCapacity),
		selected:           -1,
	}
}

func (d *MCPDashboard) Start(ctx context.Context, eventCh <-chan MCPEvent) {
	d.mu.Lock()
	if d.program != nil {
		d.mu.Unlock()
		return
	}
	d.startedAt = time.Now()
	d.mu.Unlock()

	model := &mcpDashboardModel{
		dashboard: d,
		width:     120,
		height:    40,
	}

	p := tea.NewProgram(model)
	d.mu.Lock()
	d.program = p
	d.mu.Unlock()

	go func() {
		if _, err := p.Run(); err != nil {
			log.Printf("dashboard: bubbletea exited with error: %v", err)
		}
	}()

	go func() {
		for {
			select {
			case <-ctx.Done():
				d.Stop()
				return
			case evt, ok := <-eventCh:
				if !ok {
					return
				}
				p.Send(mcpDashboardMsg{typ: "event", evt: evt})
			}
		}
	}()
}

func (d *MCPDashboard) Stop() {
	d.stopOnce.Do(func() {
		d.mu.Lock()
		p := d.program
		d.mu.Unlock()
		if p != nil {
			p.Quit()
		}
	})
}

// ---------------------------------------------------------------------------
// Bubbletea lifecycle
// ---------------------------------------------------------------------------

func (m mcpDashboardModel) Init() tea.Cmd {
	return tea.Tick(tuiRefreshMs, func(t time.Time) tea.Msg {
		return tickMsg(t)
	})
}

func (m mcpDashboardModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	d := m.dashboard

	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		m.width = msg.Width
		m.height = msg.Height
	case tea.KeyMsg:
		return m.handleKey(msg)
	case mcpDashboardMsg:
		if msg.typ == "event" {
			d.recordEvent(msg.evt)
		}
	case tickMsg:
		return m, tea.Tick(tuiRefreshMs, func(t time.Time) tea.Msg {
			return tickMsg(t)
		})
	}
	return m, nil
}

func (m mcpDashboardModel) handleKey(msg tea.KeyMsg) (tea.Model, tea.Cmd) {
	d := m.dashboard
	d.mu.Lock()
	mode := d.mode
	d.mu.Unlock()

	if mode == modeFilter {
		return m.handleFilterKey(msg)
	}

	switch msg.String() {
	case "q", "ctrl+c":
		return m, tea.Quit
	case "up", "k":
		d.handleInput("up")
	case "down", "j":
		d.handleInput("down")
	case "G":
		d.handleInput("end")
	case "g":
		d.handleInput("home")
	case "ctrl+d":
		d.handleInput("pagedown")
	case "ctrl+u":
		d.handleInput("pageup")
	case "enter":
		d.handleInput("toggle")
	case " ":
		d.handleInput("pause")
	case "c":
		d.handleInput("clear")
	case "/":
		d.handleInput("filter")
	case "escape":
		d.handleInput("escape")
	}
	return m, nil
}

func (m mcpDashboardModel) handleFilterKey(msg tea.KeyMsg) (tea.Model, tea.Cmd) {
	d := m.dashboard
	key := msg.String()

	switch key {
	case "escape":
		d.mu.Lock()
		d.mode = modeNormal
		d.filter = ""
		d.mu.Unlock()
	case "enter":
		d.mu.Lock()
		d.mode = modeNormal
		d.mu.Unlock()
	case "backspace":
		d.mu.Lock()
		if len(d.filter) > 0 {
			d.filter = d.filter[:len(d.filter)-1]
		}
		d.mu.Unlock()
	case "ctrl+u":
		d.mu.Lock()
		d.filter = ""
		d.mu.Unlock()
	default:
		if len(key) == 1 && key[0] >= 32 && key[0] < 127 {
			d.mu.Lock()
			d.filter += key
			d.mu.Unlock()
		}
	}
	return m, nil
}

func (m mcpDashboardModel) View() tea.View {
	d := m.dashboard
	state := d.snapshot()

	width := m.width
	if width <= 0 {
		width = 120
	}
	height := m.height
	if height <= 0 {
		height = 40
	}

	endpoint := state.RemoteURL
	if endpoint == "not exposed" {
		endpoint = state.LocalURL
	}

	var content string
	if state.ReqCount == 0 && state.Filter == "" {
		content = renderSetupScreen(width, height, state, endpoint)
	} else {
		content = renderLiveScreen(width, height, state, endpoint)
	}

	v := tea.NewView(content)
	v.AltScreen = true
	return v
}

// ---------------------------------------------------------------------------
// Setup screen (before first request)
// ---------------------------------------------------------------------------

func renderSetupScreen(width, height int, state dashboardSnapshot, endpoint string) string {
	top := renderTopBar(width, state, endpoint)
	bot := renderBottomBar(width, state)

	var b strings.Builder
	b.WriteString("\n")
	b.WriteString(setupHeader.Render("  localfiles-mcp"))
	b.WriteString("\n\n")
	b.WriteString(setupDim.Render("  Waiting for the first MCP request..."))
	b.WriteString("\n\n")

	b.WriteString(setupHeader.Render("  Connect"))
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("  1. Add server URL:  %s\n", setupValue.Render(endpoint)))
	b.WriteString(fmt.Sprintf("  2. Add header:      %s\n", setupValue.Render("Authorization: Bearer "+state.Token)))
	b.WriteString(fmt.Sprintf("  3. Tools:           %s\n", setupValue.Render("list_files, read_file, search_files")))
	if state.TokenAutoGenerated {
		b.WriteString(setupDim.Render("     Token was auto-generated for this session."))
		b.WriteString("\n")
	}
	b.WriteString("\n")

	b.WriteString(setupHeader.Render("  Server"))
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("  Root:      %s\n", setupValue.Render(state.RootDir)))
	b.WriteString(fmt.Sprintf("  Local:     %s\n", setupValue.Render(state.LocalURL)))
	if state.Exposed {
		b.WriteString(fmt.Sprintf("  Tailscale: %s\n", setupValue.Render(fmt.Sprintf("%s:%d%s", state.TailscaleHost, state.TailscalePort, state.ExposePath))))
	}

	body := b.String()
	bodyLines := strings.Count(body, "\n")
	topLines := 1
	botLines := 1
	padLines := height - topLines - botLines - bodyLines
	if padLines < 0 {
		padLines = 0
	}

	return top + "\n" + body + strings.Repeat("\n", padLines) + bot
}

// ---------------------------------------------------------------------------
// Live screen (table + inspector)
// ---------------------------------------------------------------------------

func renderLiveScreen(width, height int, state dashboardSnapshot, endpoint string) string {
	top := renderTopBar(width, state, endpoint)
	bot := renderBottomBar(width, state)

	// Budget: top(1) + tableHeader(1) + separator(1) + inspector(inspH) + bot(1) = 4 + inspH
	filtered := filterEvents(state.Events, state.Filter)
	inspH := inspectorRows
	tableH := height - 4 - inspH
	if tableH < 3 {
		tableH = 3
		inspH = height - 4 - tableH
		if inspH < 3 {
			inspH = 3
		}
	}

	tableHeader := renderTableHeader(width)
	tableBody := renderTableBody(width, tableH, state, filtered)
	separator := lipgloss.NewStyle().Foreground(lipgloss.Color("238")).Render(strings.Repeat("─", width))
	inspector := renderInspector(width, inspH, state)

	return top + "\n" + tableHeader + "\n" + tableBody + "\n" + separator + "\n" + inspector + "\n" + bot
}

// ---------------------------------------------------------------------------
// Top bar
// ---------------------------------------------------------------------------

func renderTopBar(width int, state dashboardSnapshot, endpoint string) string {
	uptime := time.Since(state.StartedAt).Round(time.Second)

	title := barAccent.Render("localfiles-mcp")
	ep := barDim.Render(endpoint)
	up := barDim.Render(fmt.Sprintf("up %s", uptime))

	var statusBadge string
	if state.Paused {
		statusBadge = pausedIndicator.Render(" PAUSED ")
	} else {
		statusBadge = liveIndicator.Render(" LIVE ")
	}

	counters := barStyle.Render(fmt.Sprintf("%d req  %d ok  %d err  %d unauth",
		state.ReqCount, state.OkCount, state.ErrCount, state.Unauth))

	left := title + " " + ep + " " + up + " " + statusBadge
	right := counters

	leftW := lipgloss.Width(left)
	rightW := lipgloss.Width(right)
	gap := width - leftW - rightW
	if gap < 1 {
		gap = 1
	}

	line := left + strings.Repeat(" ", gap) + right
	return lipgloss.NewStyle().
		Background(lipgloss.Color("236")).
		Width(width).
		Render(line)
}

// ---------------------------------------------------------------------------
// Bottom bar
// ---------------------------------------------------------------------------

func renderBottomBar(width int, state dashboardSnapshot) string {
	if state.Mode == modeFilter {
		prompt := filterPrompt.Render("Filter: ")
		text := filterInput.Render(state.Filter + "█")
		hint := barDim.Render("  enter:apply  esc:cancel  ctrl+u:clear")
		line := prompt + text + hint
		return lipgloss.NewStyle().
			Background(lipgloss.Color("236")).
			Width(width).
			Render(line)
	}

	hints := barDim.Render(" j/k:move  enter:expand  space:pause  /:filter  c:clear  g/G:top/bottom  q:quit")
	return lipgloss.NewStyle().
		Background(lipgloss.Color("236")).
		Width(width).
		Render(hints)
}

// ---------------------------------------------------------------------------
// Table
// ---------------------------------------------------------------------------

func renderTableHeader(width int) string {
	cols := tableColumns(width)
	var b strings.Builder
	for _, col := range cols {
		b.WriteString(fitToWidth(col.header, col.width))
		b.WriteString(" ")
	}
	return tableHeaderStyle.Width(width).Render(b.String())
}

type tableColumn struct {
	header string
	width  int
}

func tableColumns(totalWidth int) []tableColumn {
	// #(4) Time(10) Method(18) Tool(20) Client(16) Status(7) Latency(9) Size(8)
	// Minimum ~92 chars. Tool and Method get leftover space.
	fixed := 4 + 10 + 7 + 9 + 8 + 16 + len("       ") // gaps
	flex := totalWidth - fixed
	if flex < 20 {
		flex = 20
	}
	methodW := flex * 2 / 5
	toolW := flex - methodW

	return []tableColumn{
		{"#", 4},
		{"Time", 10},
		{"Method", methodW},
		{"Tool", toolW},
		{"Client", 16},
		{"Status", 7},
		{"Latency", 9},
		{"Size", 8},
	}
}

func renderTableBody(width, rows int, state dashboardSnapshot, filtered []int) string {
	if len(filtered) == 0 {
		empty := rowDim.Render("  No matching requests.")
		lines := []string{empty}
		for i := 1; i < rows; i++ {
			lines = append(lines, "")
		}
		return strings.Join(lines, "\n")
	}

	// Find selected index in filtered list
	selFilterIdx := -1
	for i, idx := range filtered {
		if idx == state.Selected {
			selFilterIdx = i
			break
		}
	}

	// Viewport calculation
	vp := clampViewport(selFilterIdx, state.Viewport, rows, len(filtered))
	end := vp + rows
	if end > len(filtered) {
		end = len(filtered)
	}

	cols := tableColumns(width)
	var lines []string

	for fi := vp; fi < end; fi++ {
		idx := filtered[fi]
		evt := state.Events[idx]
		isSelected := idx == state.Selected

		var b strings.Builder
		values := []string{
			fmt.Sprintf("%d", idx+1),
			eventTime(evt),
			truncateRunes(evt.Method, cols[2].width),
			truncateRunes(toolShortName(evt.Tool), cols[3].width),
			truncateRunes(fallback(evt.Client, "-"), cols[4].width),
			fmt.Sprintf("%d", evt.Status),
			evt.Latency.Round(time.Millisecond).String(),
			formatSize(evt.RequestSize + evt.ResponseSize),
		}
		for i, val := range values {
			b.WriteString(fitToWidth(val, cols[i].width))
			b.WriteString(" ")
		}

		row := b.String()
		if isSelected {
			row = rowSelected.Width(width).Render(row)
		} else {
			style := rowStyleForStatus(evt.Status)
			row = style.Width(width).Render(row)
		}
		lines = append(lines, row)
	}

	// Pad remaining lines
	for len(lines) < rows {
		lines = append(lines, "")
	}
	return strings.Join(lines, "\n")
}

func rowStyleForStatus(status int) lipgloss.Style {
	if status == 401 {
		return rowUnauth
	}
	if status >= 400 {
		return rowError
	}
	if status >= 200 && status < 300 {
		return rowOk
	}
	return rowNormal
}

// ---------------------------------------------------------------------------
// Inspector
// ---------------------------------------------------------------------------

func renderInspector(width, rows int, state dashboardSnapshot) string {
	if state.Selected < 0 || state.Selected >= len(state.Events) {
		content := inspectorSection.Render("Inspector") + "\n" +
			rowDim.Render("  Select a request to inspect.")
		return padToHeight(content, rows)
	}

	evt := state.Events[state.Selected]
	var lines []string

	lines = append(lines, inspectorSection.Render("Inspector")+" "+
		rowDim.Render(fmt.Sprintf("#%d", state.Selected+1)))

	lines = append(lines, inspectorRow("Method", evt.Method))
	lines = append(lines, inspectorRow("Tool", toolShortName(evt.Tool)))
	lines = append(lines, inspectorRow("Client", fallback(evt.Client, "-")))
	lines = append(lines, inspectorRow("Status", fmt.Sprintf("%d", evt.Status)))
	lines = append(lines, inspectorRow("Latency", evt.Latency.Round(time.Millisecond).String()))
	lines = append(lines, inspectorRow("Time", eventTime(evt)))
	if evt.RequestID != "" {
		lines = append(lines, inspectorRow("Request ID", evt.RequestID))
	}
	lines = append(lines, inspectorRow("Size", fmt.Sprintf("%s in / %s out",
		formatSize(evt.RequestSize), formatSize(evt.ResponseSize))))

	if state.Expanded {
		if evt.RequestParams != "" {
			lines = append(lines, "")
			lines = append(lines, inspectorSection.Render("Request Params"))
			for _, pl := range wrapText(evt.RequestParams, width-4) {
				lines = append(lines, "  "+pl)
			}
		}
		if evt.Details != "" {
			lines = append(lines, inspectorRow("Details", evt.Details))
		}
		if evt.Error != "" {
			lines = append(lines, inspectorRow("Error", rowError.Render(evt.Error)))
		}
	} else if len(lines) < rows {
		lines = append(lines, rowDim.Render("  press enter to expand"))
	}

	content := strings.Join(lines, "\n")
	return padToHeight(content, rows)
}

func inspectorRow(label, value string) string {
	return inspectorLabel.Render(label) + " " + inspectorValue.Render(value)
}

// ---------------------------------------------------------------------------
// Filter
// ---------------------------------------------------------------------------

func filterEvents(events []MCPEvent, filter string) []int {
	filter = strings.TrimSpace(filter)
	indices := make([]int, 0, len(events))
	if filter == "" {
		for i := range events {
			indices = append(indices, i)
		}
		return indices
	}

	terms := strings.Fields(strings.ToLower(filter))
	for i, evt := range events {
		if eventMatchesFilter(evt, terms) {
			indices = append(indices, i)
		}
	}
	return indices
}

func eventMatchesFilter(evt MCPEvent, terms []string) bool {
	for _, term := range terms {
		negate := false
		if strings.HasPrefix(term, "-") {
			negate = true
			term = term[1:]
		}

		matched := false
		if k, v, ok := strings.Cut(term, ":"); ok {
			matched = fieldMatch(evt, k, v)
		} else {
			blob := strings.ToLower(evt.Method + " " + evt.Tool + " " + evt.Client + " " + evt.Details + " " + evt.Error)
			matched = strings.Contains(blob, term)
		}

		if negate {
			matched = !matched
		}
		if !matched {
			return false
		}
	}
	return true
}

func fieldMatch(evt MCPEvent, key, value string) bool {
	switch key {
	case "tool":
		return strings.Contains(strings.ToLower(toolShortName(evt.Tool)), value)
	case "method":
		return strings.Contains(strings.ToLower(evt.Method), value)
	case "client":
		return strings.Contains(strings.ToLower(evt.Client), value)
	case "status":
		return fmt.Sprintf("%d", evt.Status) == value
	case "error":
		return strings.Contains(strings.ToLower(evt.Error), value)
	default:
		return false
	}
}

// ---------------------------------------------------------------------------
// Dashboard state management
// ---------------------------------------------------------------------------

func (d *MCPDashboard) handleInput(cmd string) {
	if cmd == "" {
		return
	}
	d.mu.Lock()
	defer d.mu.Unlock()

	tableRows := d.visibleTableRows()

	switch cmd {
	case "quit":
		d.stopOnce.Do(func() {
			if d.program != nil {
				d.program.Quit()
			}
		})
	case "up":
		d.selected = clamp(d.selected-1, 0, d.maxSelectable())
		d.expanded = false
	case "down":
		d.selected = clamp(d.selected+1, 0, d.maxSelectable())
		d.expanded = false
	case "home":
		d.selected = 0
		d.viewport = 0
		d.expanded = false
	case "end":
		d.selected = d.maxSelectable()
		d.expanded = false
	case "pagedown":
		d.selected = clamp(d.selected+tableRows/2, 0, d.maxSelectable())
		d.expanded = false
	case "pageup":
		d.selected = clamp(d.selected-tableRows/2, 0, d.maxSelectable())
		d.expanded = false
	case "toggle":
		if d.selected >= 0 {
			d.expanded = !d.expanded
		}
	case "pause":
		d.paused = !d.paused
	case "clear":
		d.events = d.events[:0]
		d.reqCount = 0
		d.okCount = 0
		d.errCount = 0
		d.unauth = 0
		d.selected = -1
		d.viewport = 0
		d.expanded = false
	case "filter":
		d.mode = modeFilter
		d.filter = ""
	case "escape":
		d.filter = ""
		d.mode = modeNormal
	}
	if d.selected >= 0 {
		d.viewport = clampViewport(d.selected, d.viewport, tableRows, len(d.events))
	}
}

func (d *MCPDashboard) visibleTableRows() int {
	// Approximate; will be refined by actual height in View
	return 20
}

func (d *MCPDashboard) maxSelectable() int {
	if len(d.events) == 0 {
		return 0
	}
	return len(d.events) - 1
}

func (d *MCPDashboard) recordEvent(evt MCPEvent) {
	d.mu.Lock()
	defer d.mu.Unlock()

	if d.paused {
		// Still count, but don't update selection/viewport
		d.reqCount++
		if evt.Status >= 400 || evt.Error != "" {
			d.errCount++
		} else {
			d.okCount++
		}
		if evt.Status == 401 {
			d.unauth++
		}
		if len(d.events) >= tuiLogCapacity {
			copy(d.events, d.events[1:])
			d.events[len(d.events)-1] = evt
		} else {
			d.events = append(d.events, evt)
		}
		return
	}

	if len(d.events) >= tuiLogCapacity {
		copy(d.events, d.events[1:])
		d.events[len(d.events)-1] = evt
		if d.selected > 0 {
			d.selected--
		}
		d.viewport--
	} else {
		d.events = append(d.events, evt)
	}
	d.reqCount++
	if evt.Status >= 400 || evt.Error != "" {
		d.errCount++
	} else {
		d.okCount++
	}
	if evt.Status == 401 {
		d.unauth++
	}
	if d.selected == -1 {
		d.selected = len(d.events) - 1
	}
	if d.viewport < 0 {
		d.viewport = 0
	}
	d.viewport = clampViewport(d.selected, d.viewport, d.visibleTableRows(), len(d.events))
}

// ---------------------------------------------------------------------------
// Snapshot
// ---------------------------------------------------------------------------

type dashboardSnapshot struct {
	LocalURL           string
	RemoteURL          string
	RootDir            string
	ExposePath         string
	Exposed            bool
	Token              string
	TokenAutoGenerated bool
	TailscaleHost      string
	TailscalePort      int
	StartedAt          time.Time
	ReqCount           int
	OkCount            int
	ErrCount           int
	Unauth             int
	Events             []MCPEvent
	Selected           int
	Expanded           bool
	Viewport           int
	Paused             bool
	Mode               tuiMode
	Filter             string
}

func (d *MCPDashboard) snapshot() dashboardSnapshot {
	d.mu.Lock()
	defer d.mu.Unlock()

	copied := make([]MCPEvent, len(d.events))
	copy(copied, d.events)

	return dashboardSnapshot{
		LocalURL:           d.localURL,
		RemoteURL:          d.remoteURL,
		RootDir:            d.rootDir,
		ExposePath:         d.exposePath,
		Exposed:            d.exposeActive,
		Token:              d.authToken,
		TokenAutoGenerated: d.tokenAutoGenerated,
		TailscaleHost:      d.tailscaleHost,
		TailscalePort:      d.tailscalePort,
		StartedAt:          d.startedAt,
		ReqCount:           d.reqCount,
		OkCount:            d.okCount,
		ErrCount:           d.errCount,
		Unauth:             d.unauth,
		Events:             copied,
		Selected:           d.selected,
		Expanded:           d.expanded,
		Viewport:           d.viewport,
		Paused:             d.paused,
		Mode:               d.mode,
		Filter:             d.filter,
	}
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func toolShortName(tool string) string {
	if after, ok := strings.CutPrefix(tool, "tools.call:"); ok {
		return after
	}
	return tool
}

func formatSize(bytes int) string {
	if bytes <= 0 {
		return "-"
	}
	if bytes < 1024 {
		return fmt.Sprintf("%dB", bytes)
	}
	if bytes < 1024*1024 {
		return fmt.Sprintf("%.1fK", float64(bytes)/1024)
	}
	return fmt.Sprintf("%.1fM", float64(bytes)/(1024*1024))
}

func eventTime(evt MCPEvent) string {
	if evt.Timestamp.IsZero() {
		return "--:--:--"
	}
	return evt.Timestamp.Format("15:04:05")
}

func fallback(value string, replacement string) string {
	if strings.TrimSpace(value) == "" {
		return replacement
	}
	return value
}

func boolToWord(b bool) string {
	if b {
		return "enabled"
	}
	return "disabled"
}

func fitToWidth(value string, width int) string {
	if width <= 0 {
		return ""
	}
	value = truncateRunes(value, width)
	if runeWidth(value) < width {
		value += strings.Repeat(" ", width-runeWidth(value))
	}
	return value
}

func truncateRunes(value string, maxWidth int) string {
	if maxWidth <= 0 {
		return ""
	}
	runes := []rune(value)
	if len(runes) <= maxWidth {
		return value
	}
	if maxWidth <= 1 {
		return string(runes[:maxWidth])
	}
	return string(runes[:maxWidth-1]) + "…"
}

func runeWidth(value string) int {
	return utf8.RuneCountInString(value)
}

func padToHeight(content string, rows int) string {
	lines := strings.Split(content, "\n")
	for len(lines) < rows {
		lines = append(lines, "")
	}
	if len(lines) > rows {
		lines = lines[:rows]
	}
	return strings.Join(lines, "\n")
}

func wrapText(value string, maxW int) []string {
	if maxW <= 0 {
		return []string{""}
	}
	tokens := strings.Split(value, " ")
	if len(tokens) == 0 {
		return []string{""}
	}
	lines := make([]string, 0)
	current := tokens[0]
	for i := 1; i < len(tokens); i++ {
		n := tokens[i]
		if runeWidth(current)+1+runeWidth(n) > maxW {
			lines = append(lines, padLine(current, maxW))
			current = n
			continue
		}
		current = current + " " + n
	}
	lines = append(lines, padLine(current, maxW))
	return lines
}

func padLine(value string, width int) string {
	if runeWidth(value) < width {
		return value + strings.Repeat(" ", width-runeWidth(value))
	}
	if runeWidth(value) > width {
		return truncateRunes(value, width)
	}
	return value
}

func clamp(v, minV, maxV int) int {
	if v < minV {
		return minV
	}
	if v > maxV {
		return maxV
	}
	return v
}

func clampViewport(selected, current, window int, total int) int {
	if total <= window {
		return 0
	}
	if selected < 0 {
		return current
	}
	if selected < current {
		return selected
	}
	if selected >= current+window {
		return clamp(selected-window+1, 0, total-1)
	}
	return current
}
