package main

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"time"
	"unicode/utf8"

	tea "charm.land/bubbletea/v2"
)

const (
	tuiRefreshMs      = 200 * time.Millisecond
	tuiLogCapacity    = 30
	detailLinesLimit  = 3
	logRows           = 8
	minDashboardWidth = 72
	maxDashboardWidth = 140
)

type MCPDashboardConfig struct {
	LocalURL           string
	RemoteURL          string
	RootDir            string
	ExposePath         string
	ExposeActive       bool
	AuthToken          string
	TokenAutoGenerated bool
	TailscaleHost      string
	TailscalePort      int
}

type MCPDashboard struct {
	localURL           string
	remoteURL          string
	rootDir            string
	exposePath         string
	exposeActive       bool
	authToken          string
	tokenAutoGenerated bool
	tailscaleHost      string
	tailscalePort      int

	startedAt time.Time

	mu sync.Mutex

	events []MCPEvent
	// reqCount is the total count. reqCount == len(events) because we only
	// track successful event captures from the server path. It is kept for O(1)
	// rendering and to avoid recomputing under lock.
	reqCount int
	okCount  int
	errCount int
	unauth   int

	selected int
	expanded bool
	viewport int
	program  *tea.Program
	stopOnce sync.Once
}

type mcpDashboardMsg struct {
	typ string
	evt MCPEvent
}

type tickMsg time.Time

type mcpDashboardModel struct {
	dashboard *MCPDashboard
	width     int
	height    int
}

func NewMCPDashboard(cfg MCPDashboardConfig) *MCPDashboard {
	remote := cfg.RemoteURL
	if remote == "" {
		remote = "not exposed"
	}
	return &MCPDashboard{
		localURL:           cfg.LocalURL,
		remoteURL:          remote,
		rootDir:            cfg.RootDir,
		exposePath:         cfg.ExposePath,
		exposeActive:       cfg.ExposeActive,
		authToken:          cfg.AuthToken,
		tokenAutoGenerated: cfg.TokenAutoGenerated,
		tailscaleHost:      cfg.TailscaleHost,
		tailscalePort:      cfg.TailscalePort,
		startedAt:          time.Now(),
		events:             make([]MCPEvent, 0, tuiLogCapacity),
		selected:           -1,
	}
}

func (d *MCPDashboard) Start(ctx context.Context, eventCh <-chan MCPEvent) {
	d.mu.Lock()
	if d.program != nil {
		d.mu.Unlock()
		return
	}
	d.startedAt = time.Now()
	d.mu.Unlock()

	model := &mcpDashboardModel{
		dashboard: d,
		width:     108,
		height:    30,
	}

	p := tea.NewProgram(model)
	d.mu.Lock()
	d.program = p
	d.mu.Unlock()

	go func() {
		_, _ = p.Run()
	}()

	go func() {
		for {
			select {
			case <-ctx.Done():
				d.Stop()
				return
			case evt, ok := <-eventCh:
				if !ok {
					return
				}
				p.Send(mcpDashboardMsg{typ: "event", evt: evt})
			}
		}
	}()
}

func (m mcpDashboardModel) Init() tea.Cmd {
	return tea.Tick(tuiRefreshMs, func(t time.Time) tea.Msg {
		return tickMsg(t)
	})
}

func (m mcpDashboardModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	d := m.dashboard

	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		m.width = msg.Width
		m.height = msg.Height
	case tea.KeyMsg:
		switch msg.String() {
		case "q", "ctrl+c", "Q", "ctrl+C", "x", "X":
			return m, tea.Quit
		case "up", "k", "K":
			d.handleInput("up")
		case "down", "j", "J":
			d.handleInput("down")
		case "enter", " ":
			d.handleInput("toggle")
		case "c", "C":
			d.handleInput("clear")
		}
	case mcpDashboardMsg:
		if msg.typ == "event" {
			d.recordEvent(msg.evt)
		}
	case tickMsg:
		return m, tea.Tick(tuiRefreshMs, func(t time.Time) tea.Msg {
			return tickMsg(t)
		})
	}

	return m, nil
}

func (m mcpDashboardModel) View() tea.View {
	d := m.dashboard
	state := d.snapshot()

	width := m.width
	if width <= 0 {
		width = 108
	}
	if width > maxDashboardWidth {
		width = maxDashboardWidth
	}
	if width < minDashboardWidth {
		width = minDashboardWidth
	}

	height := m.height
	if height <= 0 {
		height = 30
	}

	endpoint := state.RemoteURL
	if endpoint == "not exposed" {
		endpoint = state.LocalURL
	}

	uptime := time.Since(state.StartedAt).Round(time.Second)
	sections := []string{
		renderHeroPanel(width, state, endpoint, uptime),
		renderMetricsPanel(width, state),
	}

	if state.ReqCount == 0 {
		sections = append(sections, renderSetupPanel(width, state, endpoint))
		sections = append(sections, renderFooterPanel(width, false))
		return tea.NewView(strings.Join(sections, "\n\n"))
	}

	listPanel := renderEventListPanel(calcListWidth(width), height, state)
	detailPanel := renderDetailsPanel(calcDetailWidth(width), state)
	if width >= 112 {
		sections = append(sections, joinColumns(2, listPanel, detailPanel))
	} else {
		sections = append(sections, listPanel, detailPanel)
	}
	sections = append(sections, renderFooterPanel(width, true))

	return tea.NewView(strings.Join(sections, "\n\n"))
}

func renderHeroPanel(width int, state dashboardSnapshot, endpoint string, uptime time.Duration) string {
	status := "Ready for first request"
	if state.ReqCount > 0 {
		status = "Live request stream"
	}
	lines := []string{
		"Local Files MCP",
		status,
		fmt.Sprintf("Endpoint  %s", endpoint),
		fmt.Sprintf("Root      %s", state.RootDir),
		fmt.Sprintf("Uptime    %s", uptime.String()),
		fmt.Sprintf("Exposure  %s via %s", boolToWord(state.Exposed), state.ExposePath),
	}
	if state.Exposed {
		lines = append(lines, fmt.Sprintf("Tailnet   %s:%d", state.TailscaleHost, state.TailscalePort))
	} else {
		lines = append(lines, fmt.Sprintf("Local     %s", state.LocalURL))
	}
	return renderPanel(width, "Overview", lines)
}

func renderMetricsPanel(width int, state dashboardSnapshot) string {
	cardWidth := metricWidth(width, 4)
	cards := []string{
		renderMetricCard(cardWidth, "Requests", fmt.Sprintf("%d", state.ReqCount), "captured"),
		renderMetricCard(cardWidth, "OK", fmt.Sprintf("%d", state.OkCount), "successful"),
		renderMetricCard(cardWidth, "Errors", fmt.Sprintf("%d", state.ErrCount), "bad status"),
		renderMetricCard(cardWidth, "Unauthorized", fmt.Sprintf("%d", state.Unauth), "401s"),
	}
	if width >= 120 {
		return joinColumns(2, cards...)
	}
	if width >= 88 {
		return joinColumns(2, cards[0], cards[1]) + "\n" + joinColumns(2, cards[2], cards[3])
	}
	return strings.Join(cards, "\n")
}

func renderMetricCard(width int, label, value, caption string) string {
	return renderPanel(width, label, []string{value, caption})
}

func metricWidth(totalWidth int, columns int) int {
	gaps := (columns - 1) * 2
	width := (totalWidth - gaps) / columns
	if width < 16 {
		width = 16
	}
	return width
}

func calcListWidth(totalWidth int) int {
	if totalWidth < 112 {
		return totalWidth
	}
	return (totalWidth - 2) * 3 / 5
}

func calcDetailWidth(totalWidth int) int {
	if totalWidth < 112 {
		return totalWidth
	}
	return totalWidth - calcListWidth(totalWidth) - 2
}

func renderSetupPanel(width int, state dashboardSnapshot, endpoint string) string {
	lines := []string{
		"Connect ChatGPT",
		"1. Open ChatGPT > Settings > Advanced > Model Context Protocol",
		fmt.Sprintf("2. Add server URL: %s", endpoint),
		fmt.Sprintf("3. Add header: Authorization: Bearer %s", state.Token),
		"4. Start with list_files or read_file",
		"",
		"Waiting for the first request. The dashboard stays open so you can verify the connection path before using it.",
	}
	if state.TokenAutoGenerated {
		lines = append(lines, "Token was generated for this session.")
	}
	if state.Exposed {
		lines = append(lines, fmt.Sprintf("Tailscale route: %s:%d%s", state.TailscaleHost, state.TailscalePort, state.ExposePath))
	}
	return renderPanel(width, "Connect", lines)
}

func renderEventListPanel(width int, height int, state dashboardSnapshot) string {
	lines := []string{"Recent requests"}
	if len(state.Events) == 0 {
		lines = append(lines, "No activity yet.")
		return renderPanel(width, "Activity", lines)
	}

	visible := clamp((height-20)/2, 4, logRows)
	start := clampViewport(state.Selected, state.Viewport, visible, len(state.Events))
	end := start + visible
	if end > len(state.Events) {
		end = len(state.Events)
	}

	for i := start; i < end; i++ {
		event := state.Events[i]
		marker := " "
		if i == state.Selected {
			marker = "›"
		}
		head := fmt.Sprintf("%s %s  %s", marker, eventTime(event), summarizeEvent(event))
		tail := fmt.Sprintf("  %s  %s  #%02d", strings.ToUpper(event.Method), fallback(event.Client, "unknown"), i+1)
		lines = append(lines, head, tail)
		if i == state.Selected && state.Expanded {
			lines = append(lines, "  Expanded details are open in the inspector panel.")
		}
	}
	return renderPanel(width, "Activity", lines)
}

func renderDetailsPanel(width int, state dashboardSnapshot) string {
	if state.Selected < 0 || state.Selected >= len(state.Events) {
		return renderPanel(width, "Inspector", []string{
			"No request selected.",
			"Use j/k or the arrow keys to move once traffic starts.",
		})
	}

	event := state.Events[state.Selected]
	lines := []string{
		fmt.Sprintf("Tool      %s", fallback(event.Tool, "unknown")),
		fmt.Sprintf("Method    %s", fallback(event.Method, "unknown")),
		fmt.Sprintf("Client    %s", fallback(event.Client, "unknown")),
		fmt.Sprintf("Status    %d", event.Status),
		fmt.Sprintf("Latency   %s", event.Latency.Round(time.Millisecond)),
		fmt.Sprintf("Captured  %s", eventTime(event)),
	}

	if !state.Expanded {
		lines = append(lines,
			"",
			"Press Enter or Space to reveal full request details.",
			"Press c to clear the stream.",
		)
		return renderPanel(width, "Inspector", lines)
	}

	lines = append(lines, "")
	if strings.TrimSpace(event.Details) != "" {
		lines = append(lines, "Details", strings.TrimSpace(event.Details))
	}
	if strings.TrimSpace(event.Error) != "" {
		lines = append(lines, "Error", strings.TrimSpace(event.Error))
	}
	if strings.TrimSpace(event.Details) == "" && strings.TrimSpace(event.Error) == "" {
		lines = append(lines, "No extra request details captured for this event.")
	}
	return renderPanel(width, "Inspector", lines)
}

func renderFooterPanel(width int, live bool) string {
	lines := []string{"j/k or arrows move   enter expands   c clears   q quits"}
	if !live {
		lines = append(lines, "Setup stays visible until the first request arrives.")
	}
	return renderPanel(width, "Controls", lines)
}

func renderPanel(width int, title string, lines []string) string {
	if width < 16 {
		width = 16
	}
	inner := width - 2
	contentWidth := inner - 2
	if contentWidth < 1 {
		contentWidth = 1
	}

	var b strings.Builder
	b.WriteString("╭" + strings.Repeat("─", inner) + "╮\n")
	b.WriteString("│ " + fitToWidth(title, contentWidth) + " │\n")
	b.WriteString("├" + strings.Repeat("─", inner) + "┤\n")
	for _, line := range lines {
		if strings.TrimSpace(line) == "" {
			b.WriteString("│ " + strings.Repeat(" ", contentWidth) + " │\n")
			continue
		}
		for _, wrapped := range wrapText(line, contentWidth) {
			b.WriteString("│ " + fitToWidth(wrapped, contentWidth) + " │\n")
		}
	}
	b.WriteString("╰" + strings.Repeat("─", inner) + "╯")
	return b.String()
}

func joinColumns(gap int, blocks ...string) string {
	if len(blocks) == 0 {
		return ""
	}
	type column struct {
		lines []string
		width int
	}
	cols := make([]column, 0, len(blocks))
	maxHeight := 0
	for _, block := range blocks {
		lines := strings.Split(strings.TrimSuffix(block, "\n"), "\n")
		colWidth := 0
		for _, line := range lines {
			colWidth = max(colWidth, runeWidth(line))
		}
		cols = append(cols, column{lines: lines, width: colWidth})
		maxHeight = max(maxHeight, len(lines))
	}

	var b strings.Builder
	separator := strings.Repeat(" ", gap)
	for row := 0; row < maxHeight; row++ {
		for i, col := range cols {
			line := ""
			if row < len(col.lines) {
				line = col.lines[row]
			}
			b.WriteString(fitToWidth(line, col.width))
			if i < len(cols)-1 {
				b.WriteString(separator)
			}
		}
		if row < maxHeight-1 {
			b.WriteString("\n")
		}
	}
	return b.String()
}

func summarizeEvent(evt MCPEvent) string {
	name := evt.Tool
	if strings.TrimSpace(name) == "" {
		name = evt.Method
	}
	status := fmt.Sprintf("%d", evt.Status)
	if evt.Status >= 400 {
		status = "error " + status
	}
	return fmt.Sprintf("%s  %s  %s", name, status, evt.Latency.Round(time.Millisecond))
}

func eventTime(evt MCPEvent) string {
	if evt.Timestamp.IsZero() {
		return "--:--:--"
	}
	return evt.Timestamp.Format("15:04:05")
}

func fallback(value string, replacement string) string {
	if strings.TrimSpace(value) == "" {
		return replacement
	}
	return value
}

func fitToWidth(value string, width int) string {
	if width <= 0 {
		return ""
	}
	value = truncateRunes(value, width)
	if runeWidth(value) < width {
		value += strings.Repeat(" ", width-runeWidth(value))
	}
	return value
}

func truncateRunes(value string, maxWidth int) string {
	if maxWidth <= 0 {
		return ""
	}
	runes := []rune(value)
	if len(runes) <= maxWidth {
		return value
	}
	if maxWidth <= 1 {
		return string(runes[:maxWidth])
	}
	return string(runes[:maxWidth-1]) + "…"
}

func runeWidth(value string) int {
	return utf8.RuneCountInString(value)
}

func (d *MCPDashboard) Stop() {
	d.stopOnce.Do(func() {
		d.mu.Lock()
		p := d.program
		d.mu.Unlock()
		if p != nil {
			p.Quit()
		}
	})
}

func (d *MCPDashboard) handleInput(cmd string) {
	if cmd == "" {
		return
	}
	d.mu.Lock()
	defer d.mu.Unlock()

	switch cmd {
	case "quit":
		d.stopOnce.Do(func() {
			if d.program != nil {
				d.program.Quit()
			}
		})
	case "up":
		d.selected = clamp(d.selected-1, 0, d.maxSelectable())
		d.expanded = false
	case "down":
		d.selected = clamp(d.selected+1, 0, d.maxSelectable())
		d.expanded = false
	case "toggle":
		if d.selected >= 0 {
			d.expanded = !d.expanded
		}
	case "clear":
		d.events = d.events[:0]
		d.reqCount = 0
		d.okCount = 0
		d.errCount = 0
		d.unauth = 0
		d.selected = -1
		d.viewport = 0
		d.expanded = false
	}
	if d.selected >= 0 {
		d.viewport = clampViewport(d.selected, d.viewport, logRows, len(d.events))
	}
}

func (d *MCPDashboard) maxSelectable() int {
	if len(d.events) == 0 {
		return 0
	}
	return len(d.events) - 1
}

func (d *MCPDashboard) recordEvent(evt MCPEvent) {
	d.mu.Lock()
	defer d.mu.Unlock()

	if len(d.events) >= tuiLogCapacity {
		copy(d.events, d.events[1:])
		d.events[len(d.events)-1] = evt
		if d.selected > 0 {
			d.selected--
		}
		d.viewport--
	} else {
		d.events = append(d.events, evt)
	}
	d.reqCount++
	if evt.Status >= 400 || evt.Error != "" {
		d.errCount++
	} else {
		d.okCount++
	}
	if evt.Status == 401 {
		d.unauth++
	}
	if d.selected == -1 {
		d.selected = len(d.events) - 1
	}
	if d.viewport < 0 {
		d.viewport = 0
	}
	d.viewport = clampViewport(d.selected, d.viewport, logRows, len(d.events))
}

type dashboardSnapshot struct {
	LocalURL           string
	RemoteURL          string
	RootDir            string
	ExposePath         string
	Exposed            bool
	Token              string
	TokenAutoGenerated bool
	TailscaleHost      string
	TailscalePort      int
	StartedAt          time.Time
	ReqCount           int
	OkCount            int
	ErrCount           int
	Unauth             int
	Events             []MCPEvent
	Selected           int
	Expanded           bool
	Viewport           int
}

func (d *MCPDashboard) snapshot() dashboardSnapshot {
	d.mu.Lock()
	defer d.mu.Unlock()

	copied := make([]MCPEvent, len(d.events))
	copy(copied, d.events)

	return dashboardSnapshot{
		LocalURL:           d.localURL,
		RemoteURL:          d.remoteURL,
		RootDir:            d.rootDir,
		ExposePath:         d.exposePath,
		Exposed:            d.exposeActive,
		Token:              d.authToken,
		TokenAutoGenerated: d.tokenAutoGenerated,
		TailscaleHost:      d.tailscaleHost,
		TailscalePort:      d.tailscalePort,
		StartedAt:          d.startedAt,
		ReqCount:           d.reqCount,
		OkCount:            d.okCount,
		ErrCount:           d.errCount,
		Unauth:             d.unauth,
		Events:             copied,
		Selected:           d.selected,
		Expanded:           d.expanded,
		Viewport:           d.viewport,
	}
}

func boolToWord(b bool) string {
	if b {
		return "enabled"
	}
	return "disabled"
}

func wrapText(value string, max int) []string {
	if max <= 0 {
		return []string{""}
	}
	tokens := strings.Split(value, " ")
	if len(tokens) == 0 {
		return []string{""}
	}

	lines := make([]string, 0)
	current := tokens[0]
	for i := 1; i < len(tokens); i++ {
		n := tokens[i]
		if runeWidth(current)+1+runeWidth(n) > max {
			lines = append(lines, padLine(current, max))
			current = n
			continue
		}
		current = current + " " + n
	}
	lines = append(lines, padLine(current, max))
	if len(lines) > detailLinesLimit {
		lines = lines[:detailLinesLimit]
	}
	return lines
}

func padLine(value string, width int) string {
	if runeWidth(value) < width {
		return value + strings.Repeat(" ", width-runeWidth(value))
	}
	if runeWidth(value) > width {
		return truncateRunes(value, width)
	}
	return value
}

func clamp(v, minV, maxV int) int {
	if v < minV {
		return minV
	}
	if v > maxV {
		return maxV
	}
	return v
}

func clampViewport(selected, current, window int, total int) int {
	if total <= window {
		return 0
	}
	if selected < 0 {
		return current
	}
	if selected < current {
		return selected
	}
	if selected >= current+window {
		return clamp(selected-window+1, 0, total-1)
	}
	return current
}
